### PR TITLE
fix: do not show region in review for Azure provider

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Removes region info from Review for Azure.
For Azure we use Resource Group insted.

image

Refs HMS-2255

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
the tests do not like this, are we doing some UI assertions?
```
assert response.location == location
AssertionError: assert '' == 'eastus_1'
```

**Comment by ezr-ondrej** [comment]
/retest

Still public IP issue, I've filed IQE MR suggesting to wait for private IP instead.

**Comment by akhil-jha** [comment]
Let's merge this PR. The failure is related to aws from testing end. That will be fixed in the plugin only. 
Need this PR for integration test now

**Review by akhil-jha — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
I concur! :)

**Pull request merged**
