### PR TITLE
fix(HMS-1524): enable case insensitive search

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Make the filter of InstanceType case insensitive

### CODE REVIEW

**Comment by lzap** [comment]
Tests are red.

**Comment by ezr-ondrej** [comment]
And will be until we fix'em :( the pipeline is still broken. Let me check that out.

**Comment by lzap** [comment]
@akhil-jha do you think the pipeline is now ready

/retest

**Comment by adiabramovitch** [comment]
@akhil-jha Is the pipeline fixed?

**Pull request closed without merging**
