### PR TITLE
Add instance types filter

### PR DESCRIPTION
**Pull request by amirfefer**
I am tired of manually searching `t1.micro` all the time 🤣 

https://user-images.githubusercontent.com/11807069/187408684-e45baf67-ed41-4dfe-9d6d-ec6971451cb1.mov

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
Awesome, thanks for doing that! :)
Although I wonder, in PF guide [`typeahead`](https://www.patternfly.org/v4/components/select#typeahead) is done by only the `variant=SelectVariant.typeahead`, do we need a custom filter function? PF seems to have implemented a sane default, can't we just use that?

**Review by ezr-ondrej — DISMISSED** [review]
Works, thanks @amirfefer ! :+1:

**Comment by ezr-ondrej** [comment]
Oh the test is now failing :(

**Comment by amirfefer** [comment]
so let's use the filter input for now, tests are green

**Review by ezr-ondrej — APPROVED** [review]
Awesome addition, thanks @amirfefer ! :tada:

**Pull request merged**
