### PR TITLE
feat(HMS-2304): Nest list endpoints with 'data'

### PR DESCRIPTION
**Pull request by amirfefer**
Tested with
 https://github.com/RHEnVision/provisioning-backend/pull/638 and https://github.com/RedHatInsights/image-builder-frontend/pull/1299

Verified with a successful  aws launch

### CODE REVIEW

**Comment by akhil-jha** [comment]
Need those PRs to get merged for retest pass

**Comment by ezr-ondrej** [comment]
Any point in
/retest

**Review by ezr-ondrej — APPROVED** [review]
LGTM

**Comment by ezr-ondrej** [comment]
Shall we wait for the PR check? Will it even pass without prod promotion?

**Review by akhil-jha — APPROVED** [review]

**Pull request merged**
