### PR TITLE
feat(HMS-1271): add popular group for instances types

### PR DESCRIPTION
**Pull request by amirfefer**
Screen Shot 2023-03-31 at 15 47 37

### CODE REVIEW

**Comment by lzap** [comment]
Looks great.

**Comment by ezr-ondrej** [comment]
WDYT @MariSvirik ? :)

**Comment by MariSvirik** [comment]
What is under the divider? All types or the rest?
I'm not sure if this is visually enough to distinguish.
But the group itself is fine.

**Comment by lzap** [comment]
One UX idea: I would not show popular items in search results. Only when you open up the dropdown without typing anything. Because if we have too many items in the popular section we are doing it wrong :-)

**Comment by lzap** [comment]
What is the status?

**Comment by ezr-ondrej** [comment]
> How many popular items do we plan to have?

This is really up to us :) We need to decide on these, so if we could find ways to measure the success of this (maybe Pendo for how many users actually choose Popular instances) that'd be a great win IMO

**Comment by lzap** [comment]
To me one popular item from three major categories would be great:

* General purpose instance (all-rounder).
* CPU-optimized category (intensive tasks).
* Memory intensive category (memory intensive tasks).

Although cloud providers have many other categories and offerings (network optimized, storage optimized, ephemeral storage, SSD NVMe super fast local storage) we would sink into the rabbit hole fairly quickly. So picking just three favourite  ones make sense for me.

**Comment by adiabramovitch** [comment]
@amirfefer can fix the conflicts? I see the pipeline is fixed 🎊

**Comment by amirfefer** [comment]
@adiabramovitch, I guess this is on hold until we have more user insights

**Comment by lzap** [comment]
After chat on our todays planning, I have rewritten the Jira issue into a different story: _Implement a "bookmarking" feature for the instance type dropdown when users are able to select arbitrary amount of entries in the dropdown by clicking on some "star" icon or something like that. The favourite list is then presented at the very start of the listing so it is accessible. The data is stored in the user browser so it is available on each visit._

The reason for this was that we cannot agree on what makes a type a popular type, so let our users to decide themselves.

**Comment by amirfefer** [comment]
Closing this for now, not enough data.

**Pull request closed without merging**
