### PR TITLE
feat(HMS-2176): add info banner for notification

### PR DESCRIPTION
**Pull request by amirfefer**
Screen Shot 2023-07-18 at 18 16 25

### CODE REVIEW

**Comment by lzap** [comment]
Looks a bit too heavy for every single launch to me.

Idea: We could show this only in case a launch exceeds our wait time.

**Comment by amirfefer** [comment]
Maybe we can add a dismiss button?
But I think it more like a UX question, @MariSvirik, opinion?

**Comment by ezr-ondrej** [comment]
> for preventing mixing with production once it merged, would it be better to have a feature flag?

I'd say so :) ideally we would expose the backend flag, but that's overkill.
another solution would be to merge this once we are flipping the backend flag on, it's not great, but it is a solution :)

**Comment by MariSvirik** [comment]
dismiss button would work. But if the notifications are already set, we don't show it, right?
Which flag are we talking about?

**Comment by ezr-ondrej** [comment]
> Which flag are we talking about?

on backend we have a flag controling the notification integration being on or off (and it's off on prod now), so we need to make sure this notice is not enabled before we enable the notifications in production :)

**Comment by adiabramovitch** [comment]
Do we have a decision here?

**Comment by ezr-ondrej** [comment]
I think we decided to wait for the notifications to be enabled on prod and then merge this banner.

BTW @amirfefer while working on updating the banner in IB, I've noticed they are enabling users to close the banner, I guess that's not an issue for now, but might be something to think of as a next step if we want to keep the banner longer, it would be nice to give Users way to opt out from seeing it :)

**Review by ezr-ondrej — DISMISSED** [review]
I'm fine merging this for now :)
Or @amirfefer did you want to work on the closing?

**Comment by amirfefer** [comment]
Added a dismiss button.

**Review by ezr-ondrej — APPROVED** [review]
Works as expected! Thank you @amirfefer ! :tada:

**Pull request merged**
