### PR TITLE
ci(KONFLUX-2339): Update cloud image to konflux

### PR DESCRIPTION
**Pull request by akhil-jha**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Just needed a rebase :)

**Comment by akhil-jha** [comment]
Don't merge yet. There is some issue with frontend builds in konflux

**Comment by ezr-ondrej** [comment]
so ready to merge? :)

**Comment by akhil-jha** [comment]
> so ready to merge? :)

Yes!

**Comment by skateman** [comment]
Maybe run a retest first, seems like my command didn't do anything.

**Comment by ezr-ondrej** [comment]
It did run the CI on akhil's command :) and it "passed" :)

**Pull request merged**
