### PR TITLE
fix(HMS-2247): add spinner to instances table

### PR DESCRIPTION
**Pull request by amirfefer**
https://github.com/RHEnVision/provisioning-frontend/assets/11807069/f1938055-c4f2-4e28-9618-274aaaf406f4

### CODE REVIEW

**Comment by lzap** [comment]
LGTM nice

**Comment by akhil-jha** [comment]
Why won't the env get setup?! 😠 ughhh
/retest

**Review by lzap — APPROVED** [review]
Tests are green, thanks.

**Pull request merged**
