### PR TITLE
feat(HMSPROV-1133): add instances description after a successful launch

### PR DESCRIPTION
**Pull request by amirfefer**
This PR shows instances list after a succesfull laucnh

https://user-images.githubusercontent.com/11807069/215360024-2c8a489c-9789-468b-852d-27ebf8ce75f1.mov

### CODE REVIEW

**Comment by lzap** [comment]
WFM, this should be a temporary solution until we integrate more with the inventory.

Small suggestion: These are called "Public IP" and "Public DNS" because there are also private IPs or DNS entries for instances on AWS. Maybe to reword this, no big deal.

**Comment by lzap** [comment]
Are you going to continue on this one, or refactor this into what we talked about - backend doing the 5 second (max) wait and then providing the data in the reservation itself. So no additional refreshing is needed. We should cover 90% of all launches in a nice UX way.

**Comment by amirfefer** [comment]
> Are you going to continue on this one, or refactor this into what we talked about 

as we dicussed, i'm going to refacor the backend part and then consuming the instance data direcctly from the reservation

**Comment by amirfefer** [comment]
closed in favoe of #213

**Pull request closed without merging**
