### PR TITLE
feat: Prolong polling for Azure

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Azure reservation tends to take longer then other providers. This allows to adjust the polling lenght per provider. For Azure we add 3 extra minutes of polling.

Refs HMS-1553

### CODE REVIEW

**Review by amirfefer — COMMENTED** [review]
Thanks @ezr-ondrej ! I left a few comments

**Comment by lzap** [comment]
I am okay, tho, I would vote for having the same wait time for every provider. It is not that big of a deal I think. We already have the "taking too long" message I think.

**Comment by amirfefer** [comment]
@ezr-ondrej, what is the status here? would we want it before freeze?

**Comment by ezr-ondrej** [comment]
> @ezr-ondrej, what is the status here? would we want it before freeze?

not sure, I don't think this is great solution if it can fail, it adds complexity... I'm thinking: lets add two minutes for all the providers for now and lets rethink the approach post summit?

I'd think we can maybe poll forever and just in few seconds show "this is taking bit too long, sorry, but you can close this"

**Comment by ezr-ondrej** [comment]
I've decided just to prolong this all for one minute, lets figure out how this works in practice and then come up with a proper solution :)

**Review by lzap — APPROVED** [review]
I think this might be safe to be merged right now, up to you @amirfefer

**Pull request merged**
