### PR TITLE
feat(hms-1196): Refactor progress bar to progress steps

### PR DESCRIPTION
**Pull request by amirfefer**
This PR refactors the reservation progress page in the wizard to achieve: 

- [x] Replacing the classic progress bar with progress steps
- [x] Removing any specific cloud proivder code, for easier reuse  
- [x] Fix tests 

https://user-images.githubusercontent.com/11807069/216838224-975b81e8-e915-4f84-8642-819554cc010e.mov

https://user-images.githubusercontent.com/11807069/216838228-3a9ff8ee-ffd2-46ff-aa43-c343577911ba.mov

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
Love it :orange_heart:
I believe we have the steps wrong a bit tho.
We should pull additional steps dynamically from the reservation itself, the job is split to steps itself and we should respect it. But I'm happy to have it as a follow up. this redesign can be self contained and merged as-is :+1:

**Comment by amirfefer** [comment]
Thanks @ezr-ondrej :)

> We should pull additional steps dynamically from the reservation itself,

yes, I tried that first, but the UX looks off when all of the sudden more steps are added , maybe we could have a general endpoint for steps by provider before we render the progress bar. 

I fixed the tests 🟢 🙏

**Comment by ezr-ondrej** [comment]
Well the unit tests are fixed, but the integration tests are still broken tho :)

**Review by ezr-ondrej — APPROVED** [review]
Thanks @amirfefer ! Nice UI improvement:+1:

**Pull request merged**
