### PR TITLE
feat(HMS-2341): refactor the instance counter alert to validation

### PR DESCRIPTION
**Pull request by amirfefer**
Screen Shot 2023-08-14 at 17 09 29

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
LGTM :+1:
@avitova you've worked on it, wanna take a look as well? :)

**Comment by lzap** [comment]
We should use the same warning in sources selector when AWS permissions are insufficient.

**Comment by avitova** [comment]
I love this! It looks really good and does not take up space. TY!

**Comment by ezr-ondrej** [comment]
Thanks @amirfefer and @avitova for the review! :pray:

**Pull request merged**
